name: Playwright

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Select the Playwright test to run'
        required: true
        default: 'tests/'
        type: choice
        options:
          - tests/demo.spec.ts
          - tests/demo1.spec.ts
          - tests/demo3.spec.ts
          - tests/ # run all tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright test on Chromium
        id: playwright
        continue-on-error: true
        run: |
          npx playwright test ${{ github.event.inputs.script }} \
            --headed \
            --project=chromium \
            --reporter=list,json

      - name: Check if tests failed
        run: |
          if [ "${{ steps.playwright.outcome }}" != "success" ]; then
            echo "âš  Some tests failed! Check Playwright logs and report."
            exit 1
          fi

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
